initContainers:
  - name: init-octez-node
    image: tezos/tezos-bare:octez-v21.0-rc2
    resources:
      requests:
        memory: "32Gi"
        cpu: "8"
    command: ["sh", "-c"]
    args:
      - >
        set -e;
        if [ ! -e "/home/tezos/.initialized" ]; then
          mkdir -p /home/tezos;
          mkdir -p /home/tezos/octez-node;
          if [[ -n mainnet ]]; then
            /usr/local/bin/octez-node config init --data-dir=/home/tezos/octez-node --network "mainnet" ;
          fi;
          if [[ -n https://snapshots.eu.tzinit.org/mainnet/rolling ]]; then
            if [ ! -e "/home/tezos/snapshot" ]; then
              wget -O "/home/tezos/snapshot" "https://snapshots.eu.tzinit.org/mainnet/rolling";
            else
              echo "Snapshot /home/tezos/snapshot already exists, using it.";
            fi;
            echo "importing snapshot /home/tezos/snapshot";
            /usr/local/bin/octez-node snapshot import /home/tezos/snapshot --data-dir=/home/tezos/octez-node --no-check;
          fi;
          touch /home/tezos/.initialized;
        else
          echo "Octez node already initialized.";
        fi
    volumeMounts:
      - name: etherlink-pvc
        mountPath: /home/tezos
    securityContext:
      runAsUser: 0
  - name: init-rollup-node
    image: tezos/tezos-bare:octez-v21.0-rc2
    command: ["sh", "-c"]
    args:
      - >
        set -e;
        if [ ! -e "/home/tezos/.rollup_initialized" ]; then
          mkdir -p /home/tezos;
          mkdir -p /home/tezos/rollup-node;
          echo "creating rollup node config";
          /usr/local/bin/octez-smart-rollup-node init observer config for sr1Ghq66tYK9y3r8CC1Tf8i8m5nxh8nTvZEf \
            with operators --rpc-addr 0.0.0.0 --rpc-port 8932 --cors-origins '*' \
            --cors-headers '*' --pre-images-endpoint https://snapshots.eu.tzinit.org/etherlink-mainnet/wasm_2_0_0 \
            --acl-override allow-all --data-dir /home/tezos/rollup-node;
          if [ -n "https://snapshots.eu.tzinit.org/etherlink-mainnet/eth-mainnet.full" ]; then
            if [ ! -e "/home/tezos/rollup-snapshot" ]; then
              wget -O "/home/tezos/rollup-snapshot" https://snapshots.eu.tzinit.org/etherlink-mainnet/eth-mainnet.full;
            else
              echo "Snapshot /home/tezos/rollup-snapshot already exists, using it.";
            fi;
            echo "importing snapshot /home/tezos/rollup-snapshot";
            /usr/local/bin/octez-smart-rollup-node --endpoint https://rpc.tzkt.io/mainnet snapshot import /home/tezos/rollup-snapshot --data-dir /home/tezos/rollup-node;
          fi;
          touch /home/tezos/.rollup_initialized;
        else
          echo "Rollup node already initialized.";
        fi
    volumeMounts:
      - name: etherlink-pvc
        mountPath: /home/tezos
    securityContext:
      runAsUser: 0
  - name: init-evm-node
    image: tezos/tezos-bare:octez-evm-node-v0.5
    command: ["sh", "-c"]
    args:
      - >
        set -e;
        if [ ! -e "/home/tezos/.evm_initialized" ]; then
          mkdir -p /home/tezos;
          mkdir -p /home/tezos/evm-node;
          echo "creating EVM node config";
        /usr/local/bin/octez-evm-node init config --rollup-node-endpoint http://localhost:8932 --cors-origins '*' --cors-headers '*' --rpc-addr 0.0.0.0 --rpc-port 8545 --keep-alive --data-dir /home/tezos/evm-node;
          if [ -n "http://vps-58f6d7fc.vps.ovh.net/snapshots/evm-snapshot-sr1Ghq66tYK9y-latest.gz" ]; then
            if [ ! -e "/home/tezos/evm-snapshot" ]; then
              wget -O "/home/tezos/evm-snapshot" http://vps-58f6d7fc.vps.ovh.net/snapshots/evm-snapshot-sr1Ghq66tYK9y-latest.gz
;
            else
              echo "Snapshot /home/tezos/evm-snapshot already exists, using it.";
            fi;
            echo "importing snapshot /home/tezos/evm-snapshot";
            /usr/local/bin/octez-evm-node snapshot import /home/tezos/evm-snapshot --data-dir /home/tezos/evm-node;
          fi;
          touch /home/tezos/.evm_initialized;
        else
          echo "EVM node already initialized.";
        fi
    volumeMounts:
      - name: etherlink-pvc
        mountPath: /home/tezos
    securityContext:
      runAsUser: 0

containers:
  - name: octez-node
    image: tezos/tezos-bare:octez-v20.2
    volumeMounts:
      - name: etherlink-pvc
        mountPath: /home/tezos
    command: ["sh", "-c"]
    args:
      - >
        set -e;
        /usr/local/bin/octez-node run --data-dir=/home/tezos/octez-node --rpc-addr=0.0.0.0:8732 --allow-all-rpc 0.0.0.0
    ports:
      - containerPort: 8732
        name: http-node
    securityContext:
      runAsUser: 0
  - name: rollup-node
    image: tezos/tezos-bare:octez-v20.2
    volumeMounts:
      - name: etherlink-pvc
        mountPath: /home/tezos
    command: ["sh", "-c"]
    args: 
      - >
        set -e;
        export PATH=$PATH:/usr/local/bin;
        echo "starting rollup node";
        /usr/local/bin/octez-smart-rollup-node --endpoint http://localhost:8732 run --data-dir /home/tezos/rollup-node;
    ports:
      - containerPort: 8932
        name: http-rollup
    securityContext:
      runAsUser: 0
  - name: evm-observer
    image: tezos/tezos-bare:octez-evm-node-v0.5
    volumeMounts:
      - name: etherlink-pvc
        mountPath: /home/tezos
    command: ["sh", "-c"]
    args:
      - >
        su tezos;
        set -e;
        ls -l /usr/local/bin/octez-evm-node;
        chmod +x /usr/local/bin/octez-evm-node;
        export PATH=$PATH:/usr/local/bin;
        echo "creating evm node config";
        /usr/local/bin/octez-evm-node run observer --finalized-view --evm-node-endpoint https://relay.mainnet.etherlink.com --data-dir=/home/tezos/evm-node;
    ports :
      - containerPort: 8545
        name: http-evm
    securityContext:
      runAsUser: 0